trigger: none
pr: none

resources:
  repositories:
  - repository: testrepo
    type: git
    endpoint: MyTest
    name: bashad895/MyTest
    ref: main

steps:
- checkout: testrepo
  path: 'MyTest'
- template: /MyTest/Nesttest.yaml@testrepo
   




