trigger: none
pr: none

resources:
  repositories:
  - repository: testrepo
    type: git
    endpoint: MyTest
    name: bashad895/TEST1
    ref: main

extends:
  template: /MyTest/nesttest.yaml@testrepo
  parameters:
      buildType: 'CI'  
      agentPool: 'gdi-agents-pool-azvm-dev'


